spring:
  application:
    name: Pocket-Bank_plus
  datasource: # 数据库配置已切换为 TiDB 云数据库
    url: jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/pocket_bank?useSSL=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&reconnect=true
    username: 48NouLV9vQyeye8.root
    password: "Lh3kiZWgNlJ3KsSg"
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080  # 项目启动端口
  servlet:
    context-path: /demo  # 项目访问路径前缀
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    org.springframework.web: INFO  # 日志级别
    com.demo.mapper: DEBUG   # 自定义包的日志级别

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml  # 指定Mapper XML文件的位置
  # 【🔥根据你的截图完美修正】你的实体类在 pojo 目录下，别名包路径必须改成下面这样！
  type-aliases-package: com.example.pocketbank_plus.pojo  
  configuration:
    map-underscore-to-camel-case: true      # 下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印SQL
